spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: althaf
    password: althaf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    url: jdbc:postgresql://localhost:5433/product
    user: althaf
    password: althaf



server:
  port: 8050

